### ISSUE TITLE
Problem with flipBehavior

### ISSUE THREAD

**Issue by bonzoSPb** [atomiks/tippy.js-react#147] opened 2019-10-25 06:49 UTC
If i set placement="right" and flipBehavior any value - tooltip move left around 5px before hide. How fix this?

![tooltip](https://user-images.githubusercontent.com/3990514/67549344-af0c5500-f70c-11e9-90d8-2003693ffc4a.gif)

**Comment by atomiks** [comment] 2019-10-25 07:02
Have you got a CodeSandbox repro?

Not experiencing problem here: https://codesandbox.io/s/mystifying-firefly-i54gs

**Comment by bonzoSPb** [comment] 2019-10-29 05:11
With boostrap and 
html,
body,
#root {
  height: 100%;
}
.form-signin {
  margin: auto;
}
its happaned
You can check here: https://codesandbox.io/s/pensive-smoke-cz4bu

**Comment by atomiks** [comment] 2019-10-29 05:25
The problem isn't happening in the sandbox?

**Comment by bonzoSPb** [comment] 2019-10-29 05:38
Happening in my link - https://codesandbox.io/s/pensive-smoke-cz4bu
Google Chrome 78.0.3904.70
![error](https://user-images.githubusercontent.com/3990514/67740569-53510d00-fa27-11e9-9ad1-d867d56d5fc5.gif)

**Comment by atomiks** [comment] 2019-10-29 05:44
For me on Mac:

Chrome: doesn't happen
Firefox: doesn't happen
Safari: happens

It has to do with the `popperInstance` getting recreated upon render (due to the `flipBehavior` array reference changing between renders). If you extract the array to a constant above `App()` and pass that in, it's fixed. (This is also a lot better for performance since the popperInstance won't constantly change each render - this should be on the README).

However, it shouldn't really happen, so it's a bug that should be fixed in the core library

**Comment by atomiks** [comment] 2020-02-07 06:11
It's almost certainly fixed in Popper 2 (coming soon), and there's a workaround for this right now by memoizing the props, so I'll close this now.

**Closed by atomiks** 2020-02-07 06:11 UTC
Labels: bug
