### ISSUE TITLE
Uncaught TypeError: Object(...) is not a function

### ISSUE THREAD

**Issue by hovoodd** [atomiks/tippy.js-react#63] opened 2019-03-06 12:21 UTC
After install and import I get this error in browser console:

![image](https://user-images.githubusercontent.com/23063254/53880777-f2ea0700-4022-11e9-8071-b1907ba7d12e.png)

184 line is:

```js
/* 184 */ var Tippy$1 = Object(react__WEBPACK_IMPORTED_MODULE_0__["forwardRef"])(function TippyWrapper(props, _ref) {
  return react__WEBPACK_IMPORTED_MODULE_0__["default"].createElement(Tippy, props, Object(react__WEBPACK_IMPORTED_MODULE_0__["cloneElement"])(props.children, {
    ref: function ref(node) {
      preserveRef(_ref, node);
      preserveRef(props.children.ref, node);
    }
  }));
});
```

What am I doing wrong? 😢 

React: 16.8.4
@tippy.js/react: 2.1.1

**Comment by atomiks** [comment] 2019-03-06 12:34
Can you show your code?

**Comment by hovoodd** [comment] 2019-03-06 12:36
@atomiks I literally do nothing, just import package

```js
import Tippy from '@tippy.js/react';
```

**Comment by atomiks** [comment] 2019-03-06 12:37
Try deleting node_modules and reinstalling everything fresh. It sounds like a webpack and not a problem with this lib because I can import on CodeSandbox/CRA just fine

**Comment by hovoodd** [comment] 2019-03-06 12:55
Error remained after reinstallation. `react` and `react-dom` versions correct 😭. At first, I also thought that the problem was with the `webpack`, but it is reproduced only in this package 🤷‍♂️.

**Comment by atomiks** [comment] 2019-03-06 13:03
It's definitely a problem with webpack, since it works fine in CRA/CodeSandbox which use webpack too...

Might need to post your webpack config here

**Comment by hovoodd** [comment] 2019-03-06 15:02
Webpack config is pretty simple 

```js
module.exports = {
  mode: 'development',

  entry: {
    main: [
      '@babel/polyfill',
      './index.jsx',
    ],
    mobile: [
      '@babel/polyfill',
      './mobile/index.js',
    ],
  },

  output: {
    path: `${__dirname}/static/`,
    publicPath: '/static-web/',
    filename: '[name].js',
  },

  context: path.resolve(__dirname, './'),

  module: {
    rules: [
      {
        test: /\.jsx?$/,
        exclude: /node_modules/,
        use: ['babel-loader'],
      },
      {
        test: /\.pcss$/,
        use: [
          { loader: 'style-loader' },
          {
            loader: 'css-loader',
            options: {
              modules: true,
              importLoaders: 1,
              camelCase: true,
              localIdentName: '[local]_[hash:base64:5]',
            },
          },
          { loader: 'postcss-loader' },
        ],
      },
      {
        test: /\.css$/,
        use: ['style-loader', 'css-loader'],
      },
    ],
  },

  devtool: 'eval',

  resolve: {
    modules: ['./', 'node_modules'],
    extensions: ['.js', '.jsx', '.pcss'],
    alias: {
      'react-dom': '@hot-loader/react-dom',
    },
  },

  plugins: [new webpack.NoEmitOnErrorsPlugin()],
};
```

**Comment by hovoodd** [comment] 2019-03-06 15:04
I also have this warning in docker container logs

```
WARNING in ./node_modules/@tippy.js/react/esm/index.js 189:21-27
"export 'useRef' was not found in 'react'
```

**Comment by atomiks** [comment] 2019-03-06 15:07
> "export 'useRef' was not found in 'react'

You definitely aren't on the latest version of React. Something strange is happening to not have it update properly lol?

**Comment by hovoodd** [comment] 2019-03-06 15:17
But I use hooks in my app and they work properly 🌝

**Comment by atomiks** [comment] 2019-03-06 15:26
🤯

https://unpkg.com/@tippy.js/react@2.1.1/esm/index.js

Nothing here indicates any problems..

**Comment by atomiks** [comment] 2019-03-07 06:27
Another link.
- https://github.com/webpack/webpack/issues/7378

I'm going to have to close this because it's not a problem with this library, it's an environment/bundler issue. A fully reproducing link is required to debug this fruther.

**Closed by atomiks** 2019-03-07 06:27 UTC

**Comment by mwalkerr** [comment] 2020-06-28 01:20
In case anyone else is having this issue after updating their webpack config's `resolve.modules` entry, make it sure contains the plain `"node_modules"` so that webpack can resolve dependencies using `node_modules` embedded in package. The `node_modules` embedding happens when a package depends on a different version of a package that already exists in the root `node_modules`
