### ISSUE TITLE
Navbar overflowing on viewport (on the right.)

### ISSUE THREAD

**Issue by arianitu** [atomiks/tippy.js-react#168] opened 2020-02-11 15:54 UTC
I'm trying to use this library and anything I show seems to overflow passed the viewport on the right. Strangely enough, if I set boundary="asdlmas" as a random string value (I accidentally made a typo.) it seems to fix the issue.

Basically I have a navbar and I'm using tippy to show it, once I scale the window to be smaller, it overflows passed the viewport to the right.

Any suggestions, here is my settings where it works.. but if I use boundary="viewport" for example, it breaks and overflows.

```
import Tippy from '@tippy.js/react';
import 'tippy.js/dist/svg-arrow.css';
import 'tippy.js/animations/scale-subtle.css';

      <Tippy
        animation={"scale-subtle"}        
        content={profileDropdown}
        offset={"100,10"}
        interactive={true}
        sticky={true}
        visible={isOpened}
        arrow={true}
        onHide={closeProfile}
        boundary="dsdsf"
        flip={false}
        placement="bottom">
          <ProfileButton />
     </Tippy>
```

**Comment by atomiks** [comment] 2020-02-11 15:57
It's likely due to `interactive={true}` which appends it to the `<ProfileButton />` parent node, and Popper 1's positioning is broken in various cases. Does it work if you do `appendTo={document.body}`? (needs focus management in that case)

**Comment by arianitu** [comment] 2020-02-11 16:20
@atomiks  It looks like the issue was that I did not include `import 'tippy.js/dist/tippy.css';`

I think I removed the import to remove the black styling, is there a way to remove the black styling and keep the positioning that is required from tippy.css?

**Comment by arianitu** [comment] 2020-02-11 16:30
@atomiks Oh weird, so it looks like it is `arrow={true}` without a `import 'tippy.js/dist/tippy.css';`

If I set `arrow={false}`, I do not have to import `tippy.css`. Is it okay to not import `tippy.css` to prevent the default styling or you think that's a bad idea?

**Comment by atomiks** [comment] 2020-02-12 12:03
There are a couple gotchas like `pointer-events` & iOS "click outside" when not importing the CSS, but other than that it's fine. 

I'd assume Popper is having a problem with the arrow calculation but it's hard to say without a reproduction

**Comment by arianitu** [comment] 2020-02-13 23:50
@atomiks Hmm, ideally we would import it then. So do we need to override all the black background styles then with our own theme?

**Comment by atomiks** [comment] 2020-02-14 12:28
Yes, it's designed to be overridden easily / a good base though

**Comment by atomiks** [comment] 2020-02-20 08:50
This will likely be fixed in the next major which uses Popper 2 (coming by the end of this month)

**Closed by atomiks** 2020-02-20 08:50 UTC
