### ISSUE TITLE
[5.2.1] Error: Cannot read property 'clientX' of undefined

### ISSUE THREAD

**Issue by mattleonowicz** [atomiks/tippy.js-react#169] opened 2020-02-17 12:46 UTC
I get this error in the console
```
Uncaught TypeError: Cannot read property 'clientX' of undefined
    at onMouseMove (tippy.esm.js:411)
    at triggerLastMouseMove (tippy.esm.js:397)
```
Tooltip renders initially at the top left of a window, and then when I move the mouse, it positions itself where it should be (following the cursor from now on)

I have used Tippy like so: (just the relevant code)
```
import Tippy from '@tippy.js/react';
import { followCursor } from 'tippy.js';
...

const [isTooltipVisible, setIsTooltipVisible] = useState(false);
return (
<Tippy
  plugins={[followCursor]}
  followCursor
  content="Save layout changes to edit this widget."
  visible={isTooltipVisible}
  trigger="manual"
>
  <SomeStyledComponent onClick={() => setIsTooltipVisible(true)}>...</SomeStyledComponent>
<Tippy>
);
```

When I click on my component I get this error in the console.

<img width="687" alt="Screen Shot 2020-02-17 at 13 43 12" src="https://user-images.githubusercontent.com/9438872/74654839-8280bb00-518b-11ea-8cc7-17ece09d4533.png">

**Comment by atomiks** [comment] 2020-02-17 12:51
Is this caused by 5.2.1 or did it happen in 5.2.0 as well?

**Comment by mattleonowicz** [comment] 2020-02-17 12:57
I thought the same because there was a change around this place in 5.2.1, but unfortunately 5.2.0 has it too

**Comment by atomiks** [comment] 2020-02-17 13:15
I'm glad it's not a regression at least 😅 

I think this is the problem: https://github.com/atomiks/tippyjs/blob/281515438452c5026c9c24bed7e9821a4327c892/src/plugins/followCursor.ts#L212

The React component calls `.setProps()` which calls the `onAfterUpdate` callback, which triggers the `onMouseMove` handler, but the `lastMouseMoveEvent` is not yet defined which is what gets passed in. It first gets defined by `onShow()` which has not happened yet.

There's also only limited support for `followCursor` + manual trigger `.show()` as it just uses `clientX: 0` + `clientY: 0` as a base before the `mousemove` event handler kicks in, so it should probably be improved somehow as well. We need to be "listening" to the events before we can register the event listener to know the cursor position... 🤔 

I can take a look tomorrow, you're free to make a PR if you can solve this error (and possibly the limitation mentioned above) in the meantime.

**Comment by mattleonowicz** [comment] 2020-02-17 13:31
Right. Actually it makes perfect sense. Thanks for the explanation of the issue. Given the information I managed to work around it using `trigger="click"`, and just manipulated `enabled` flag and `onShown` handler to decide when to show and hide it.

Listening to events before (even if trigger="manual") sounds like the only option.
I'm not sure if I'll be able implement that any time soon though :(

**Comment by atomiks** [comment] 2020-02-20 08:51
This error is fixed in the next major which uses Popper 2 (coming by the end of this month)

**Closed by atomiks** 2020-02-20 08:51 UTC

**Comment by andi1984** [comment] 2020-05-13 07:27
Just FYI:

For me it seems that the issue got introduced with "popper.js": "^1.16.0" or some other change within Tippy.js v 5.0.4
